spring:
  application:
  name: chatGPT-lesson
notification:
  default-channel: email

  email:
    enabled: true
    host: smtp.example.com
    port: 587
    from: noreply@example.com
  console:
    enabled: true
  slack:
    enabled: true
    webhook-url: slack-url.com