spring:
  application:
  name: chatGPT-lesson
notification:
  enabled: true
  default-channel: email

  email:
    enabled: true
    host: smtp.example.com
    port: 587
    from: noreply@example.com
## 위와 같이 하면 등록되는 빈은
##    ConsoleNotificationSender
##    EmailNotificationSender
##    NotificationClient
##    NotificationProperties

## console 끄고싶으면 아래 조건 추가
#  console:
#    enabled: false